apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-demo-deployment
  labels:                     
    app: ms-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-demo
  template:
    metadata:
      labels:
        app: ms-demo
    spec:
      containers:
      - name: ms-demo-docker
        image: anovoa1975/ms-demo-docker:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8087