server:
  port: 8092
  servlet:
    context-path: /ms-alumno

  error:
    include-details: always

# MySQL

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms01_2021_alumno?serverTimezone=GMT-6
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update