apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gestion-alumno-deployment
  labels:                     
    app: ms-gestion-alumno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-gestion-alumno
  template:
    metadata:
      labels:
        app: ms-gestion-alumno
    spec:
      containers:
      - name: ms-gestion-alumno
        image: anovoa1975/ms-gestion-alumno:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8092
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-user-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-credentials
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url