apiVersion: v1
kind: Service
metadata:                     
  name: ms-gestion-alumno-service
  labels:                   
    app: ms-gestion-alumno
spec:                         
  type: LoadBalancer 
  selector:
    app: ms-gestion-alumno
  ports:
  - name: http
    port: 8092
    targetPort: 8092