apiVersion: v1
kind: Service
metadata:
  name: db-mysql-service
  labels:
    name: db-mysql
    app: ms-demo-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: db-mysql-pod
    app: ms-demo-app

  type: NodePort