CREATE TABLE PRODUCTO
(
	ID NUMERIC(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR2(280) NOT NULL UNIQUE,
	PRECIO NUMERIC(6,2) NOT NULL ,
	STOCK NUMERIC(4) NOT NULL,
	ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

create SEQUENCE SEQ_PRODUCTO;

   INSERT INTO PRODUCTO(ID,NOMBRE,PRECIO,STOCK)
  VALUES(SEQ_PRODUCTO.NEXTVAL,'Proyector ViewSonic RCP01051',1500,10);
   
  INSERT INTO PRODUCTO(ID,NOMBRE,PRECIO,STOCK) 
  VALUES(SEQ_PRODUCTO.NEXTVAL,'Laptop ASUS VivoBook Pro Core i7 7th Gen',4500,5);
  
  COMMIT;
  
  SELECT ID,NOMBRE,PRECIO,STOCK,ESTADO FROM PRODUCTO;
