CREATE TABLE TALLER
(
	ID_TALLER NUMERIC(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR2(280) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR2(400) NOT NULL ,
	DURACION NUMERIC(2) NOT NULL,
	ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE TABLE TEMA
(
	ID_TEMA NUMERIC(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR2(280) NOT NULL UNIQUE,
	ID_TALLER NUMERIC(6) NOT NULL REFERENCES TALLER(ID_TALLER),  
	ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

create sequence SEQ_TALLER;

create sequence SEQ_TEMA;

  INSERT INTO TALLER(ID_TALLER,NOMBRE,DESCRIPCION,DURACION)
  VALUES(SEQ_TALLER.NEXTVAL,'Java 11','Nuesvas características',20);
  
  INSERT INTO TALLER(ID,NOMBRE,DESCRIPCION,DURACION) 
  VALUES(SEQ_TALLER.NEXTVAL,'Angular 7','Mejoras en arquitectura',20);
  
  COMMIT;
  
  SELECT ID,NOMBRE,DESCRIPCION,DURACION,ESTADO FROM TALLER;

    
  INSERT INTO TEMA(ID_TEMA,NOMBRE,ID_TALLER) 
  VALUES(SEQ_TEMA.NEXTVAL,'Introduccion a Java 11',1);
  INSERT INTO TEMA(ID_TEMA,NOMBRE,ID_TALLER) 
  VALUES(SEQ_TEMA.NEXTVAL,'Var, Garbaje Collector',1);
  INSERT INTO TEMA(ID_TEMA,NOMBRE,ID_TALLER) 
  VALUES(SEQ_TEMA.NEXTVAL,'Proyecto modelo',1);
  
  SELECT ID_TEMA,NOMBRE,ID_TALLER FROM TEMA;

  
  INSERT INTO TEMA(ID_TEMA,NOMBRE,ID_TALLER) 
  VALUES(SEQ_TEMA.NEXTVAL,'Introduccion a Angular 7',2);
  INSERT INTO TEMA(ID_TEMA,NOMBRE,ID_TALLER) 
  VALUES(SEQ_TEMA.NEXTVAL,'Mejoras en la Arquitectura',2);
  INSERT INTO TEMA(ID_TEMA,NOMBRE,ID_TALLER) 
  VALUES(SEQ_TEMA.NEXTVAL,'Caso practico',2);

  
    SELECT ID_TEMA,NOMBRE,ID_TALLER FROM TEMA;
