use ms_02_2022_clientes;

CREATE TABLE CLIENTE(
    ID_CLIENTE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    RAZON_SOCIAL VARCHAR(260) NOT NULL UNIQUE,
    RUC CHAR(11) NOT NULL UNIQUE,
    DIRECCION VARCHAR(400) NOT NULL,
    TELEFONO VARCHAR(20) NULL,
    CORREO VARCHAR(60) NULL,
    ESTADO CHAR(1) DEFAULT '1' NOT NULL 
);


INSERT INTO CLIENTE(RAZON_SOCIAL,RUC,DIRECCION,TELEFONO,CORREO)
VALUES('CLARO EMPRESAS','20544987258','AV. LARCO 237-SAN ISIDRO','456-4574','contacto@claro.com.pe'),
('TELEFONICA EMPRESAS','20544987211','AV. LARCO 238-SAN ISIDRO','456-4575','contacto@telefonica.com.pe');

COMMIT;

SELECT ID_CLIENTE,RAZON_SOCIAL,RUC,DIRECCION,TELEFONO,CORREO FROM CLIENTE;