 CREATE TABLE "PROYECTO01"."TBL_AVI_VEHICULO" 
   ("N_ID_VEHI" NUMBER(6,0) NOT NULL ENABLE, 
	"C_MAR_VEHI" CHAR(2 BYTE) NOT NULL ENABLE, 
    "C_MOD_VEHI" CHAR(2 BYTE) NOT NULL ENABLE, 
    "C_PLA_VEHI" VARCHAR2(8 BYTE) NOT NULL ENABLE,       
    "N_CIL_VEHI" NUMBER(6,2) NOT NULL ENABLE,    
    "N_EJE_VEHI" NUMBER(6,2) NOT NULL ENABLE,
    "N_PES_VEHI" NUMBER(6,2) NOT NULL ENABLE, 
    "N_ALT_VEHI" NUMBER(6,2) NOT NULL ENABLE,  
	"N_EST_VEHI" CHAR(1 BYTE) DEFAULT '1' NOT NULL ENABLE, 
    "N_ACT_VEHI" CHAR(1 BYTE) DEFAULT '1' NOT NULL ENABLE,
	 PRIMARY KEY ("N_ID_VEHI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("C_PLA_VEHI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


CREATE SEQUENCE SEQ_VEHICULO;




SELECT * FROM "PROYECTO01"."TBL_AVI_VEHICULO";