 CREATE TABLE "PROYECTO01"."TBL_AVI_PROVEEDOR" 
   ("N_ID_PROV" NUMBER(6,0) NOT NULL ENABLE, 
	"C_RAZSOC_PROV" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
    "C_RUC_PROV" NUMBER(11,0) NOT NULL ENABLE, 	
    "C_DNI_PROV" NUMBER(8,0) NOT NULL ENABLE, 
    "C_EMAIL_PROV" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "C_TEL_PROV" NUMBER(9,0) NOT NULL ENABLE, 
    "C_DIR_PROV" VARCHAR2(150 BYTE) NOT NULL ENABLE,
    "C_REP_PROV" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
    "N_TIPO_PROV" CHAR(1 BYTE) NOT NULL ENABLE,  
	"N_EST_PROV" CHAR(1 BYTE) DEFAULT '1' NOT NULL ENABLE, 
    "N_ACT_PROV" CHAR(1 BYTE) DEFAULT '1' NOT NULL ENABLE,
	 PRIMARY KEY ("N_ID_PROV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("C_RAZSOC_PROV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE SEQUENCE SEQ_PROVEEDOR;




SELECT * FROM "PROYECTO01"."TBL_AVI_PROVEEDOR";