server:
  port: 8082
    
# My SQL #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PROYECTO01
    password: Admin123
    driver-class-name: oracle.jdbc.driver.OracleDriver
  
# Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8890

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"