server:
  port: 8081
    
# My SQL #
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/proyecto01?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Admin123
    driverClassName: com.mysql.cj.jdbc.Driver
  
# Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8890

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"