CREATE TABLE CLIENTE(
  ID_CLIENTE NUMERIC(4) NOT NULL PRIMARY KEY,
  RAZON_SOCIAL VARCHAR2(240) NOT NULL UNIQUE,
  RUC VARCHAR2(11) NOT NULL UNIQUE,
  DIRECCION VARCHAR2(400) NOT NULL ,
  TELEFONO VARCHAR2(80) NOT NULL ,
  COMENTARIO VARCHAR2(4000) NOT NULL 
);
  
CREATE SEQUENCE SEQ_CLIENTE
MINVALUE 1 
INCREMENT BY 1 
START WITH 1
NOCACHE;

INSERT INTO CLIENTE(ID_CLIENTE,RAZON_SOCIAL,RUC,DIRECCION,TELEFONO,COMENTARIO) 
VALUES (SEQ_CLIENTE.NEXTVAL, 'América Móvil Perú SAC','20467534026',
'Arriola 480 – La Victoria, Lima','+56 (2) 29410300',' ');

INSERT INTO CLIENTE(ID_CLIENTE,RAZON_SOCIAL,RUC,DIRECCION,TELEFONO,COMENTARIO) 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Telefonica del Peru','20100017491',
'Calle Schell 310 - Lima','(01)2106245',' ');

COMMIT;

ALTER TABLE CLIENTE
ADD ESTADO CHAR(1) DEFAULT '1';

SELECT ID_CLIENTE,RAZON_SOCIAL,RUC,DIRECCION,TELEFONO,COMENTARIO,ESTADO FROM CLIENTE;


