CREATE TABLE PEDIDO(
    ID_PEDIDO NUMERIC(6) NOT NULL PRIMARY KEY,
    ID_CLIENTE NUMERIC(6) NOT NULL,
    GLOSA VARCHAR2(240) NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    
    TOTAL NUMERIC(9,2) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_PEDIDO;

INSERT INTO PEDIDO(ID_PEDIDO,ID_CLIENTE,GLOSA,TOTAL) VALUES(SEQ_PEDIDO.NEXTVAL, 1,'Orden demo',6090);
COMMIT;
SELECT * FROM PEDIDO;

CREATE TABLE PEDIDO_ITEM(
    ID_PEDIDO_ITEM NUMERIC(6) NOT NULL PRIMARY KEY,
    ID_PEDIDO NUMERIC(6) REFERENCES PEDIDO(ID_PEDIDO),
    ID_PRODUCTO NUMERIC(6) NOT NULL,
    CANTIDAD NUMERIC(6) NOT NULL,
    PRECIO NUMERIC(6,2) NOT NULL,
    SUB_TOTAL NUMERIC(9,2) NOT NULL,
    
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_PEDIDO_ITEM;

INSERT INTO PEDIDO_ITEM(ID_PEDIDO_ITEM,ID_PEDIDO,ID_PRODUCTO,CANTIDAD,PRECIO,SUB_TOTAL) VALUES(SEQ_PEDIDO_ITEM.NEXTVAL, 1,1,3,30,90);
INSERT INTO PEDIDO_ITEM(ID_PEDIDO_ITEM,ID_PEDIDO,ID_PRODUCTO,CANTIDAD,PRECIO,SUB_TOTAL) VALUES(SEQ_PEDIDO_ITEM.NEXTVAL, 1,2,1,6000,6000);

COMMIT;
SELECT * FROM PEDIDO_ITEM;
