
 
 CREATE TABLE "PROYECTO01"."TBL_AVI_EMPRESA" 
   ("N_ID_EMP" NUMBER(6,0) NOT NULL ENABLE, 
	"C_NOM_EMP" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
    "C_RUC_EMP" NUMBER(11,0) NOT NULL ENABLE, 	
    "C_EMAIL_EMP" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "C_TEL_EMP" NUMBER(9,0) NOT NULL ENABLE, 
    "C_DIR_EMP" VARCHAR2(150 BYTE) NOT NULL ENABLE,
    "C_REP_EMP" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
    "N_TIPO_PROV" CHAR(1 BYTE) NOT NULL ENABLE,  
	"N_EST_EMP" CHAR(1 BYTE) DEFAULT '1' NOT NULL ENABLE, 
    "N_ACT_EMP" CHAR(1 BYTE) DEFAULT '1' NOT NULL ENABLE,
	 PRIMARY KEY ("N_ID_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("C_NOM_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


CREATE SEQUENCE SEQ_EMPRESA;


COMMIT;

SELECT * FROM "PROYECTO01"."TBL_AVI_EMPRESA";